### ISSUE TITLE
Actual site contents?

### ISSUE THREAD

**Issue by apjanke** [packagecontrol/packagecontrol.github.io#2]
Is there a repo with the actual site contents? I found a few typos in the site's text, and I’d like to submit a PR for that.

**Comment by FichteFoll** [comment]
This *is* the exact repo for the website. Maybe you could explain what you are looking for?

**Comment by apjanke** [comment]
I think I was actually looking for https://github.com/wbond/packagecontrol.io. I'm looking for the repo with the contents for https://packagecontrol.io/docs.

**Comment by apjanke** [comment]
Yep, I was looking for https://github.com/wbond/packagecontrol.io. Closing.

**Comment by FichteFoll** [comment]
Whops, I was a bit quick on the response and didn't read the repo title propery. I see that you found the proper repo, however.

By the way, this repo is the source code for https://packagecontrol.github.io/, which is used to show a list of available dependencies because we don't have that on the main site currently.
